#!/usr/bin/env bash                                                                                                                                   
#Update package lists and install Nginx                                                                                                               

apt-get update
apt-get install -y nginx

#Configure Nginx                                                                                                                                      
sudo echo "server {                                                                                                                                   
    listen 80;                                                                                                                                        
    root /var/www/html;                                                                                                                               
    index index.html;                                                                                                                                 
    location / {                                                                                                                                      
        try_files \$uri \$uri/ =404;                                                                                                                  
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;                                                                                               
        fastcgi_index index.php;                                                                                                                      
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;                                                                           
        include fastcgi_params;                                                                                                                       
    }                                                                                                                                                 
}" > /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default


#Restart Nginx                                                                                                                                        
sudo /etc/init.d/nginx restart

#Create HTML file with Hello World                                                                                                                    
echo "<html><body>Hello World!</body></html>" | sudo tee /var/www/html/index.html